# -*- coding: utf-8 -*-
"""lego.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VtoZ5Hk_LqWaPto_lvrGSd1DBkei-4Ec

hi its a test
"""

import pandas as pd
import matplotlib.pyplot as plt
colors = pd.read_csv("colors.csv")
colors.head()

colors['name'].nunique()

colors.groupby('is_trans').count()

colors.is_trans.value_counts()

"""colors  is done

now time for sets of lego
"""

sets = pd.read_csv('sets.csv')
sets.head()

sets.tail()

sets.sort_values('year').head()

sets[sets['year'] == 1949]

sets.sort_values('num_parts',ascending=False).head()

set_by_year = sets.groupby('year').count()
set_by_year['set_num'].head()

set_by_year['set_num'].tail()

set_by_year['set_num'].max()

set_by_year['set_num'].idxmax()

plt.plot(set_by_year.index,set_by_year.set_num)

plt.plot(set_by_year.index[:-2],set_by_year.set_num[:-2])

theme_by_year = sets.groupby('year').agg({'theme_id':pd.Series.nunique})
theme_by_year.head()

theme_by_year.tail()



ax1 = plt.gca()
ax2 = ax1.twinx()
plt.plot(set_by_year.index[:-2],set_by_year.set_num[:-2])
plt.plot(theme_by_year.index[:-2],theme_by_year.theme_id[:-2])

parts_per_set = sets.groupby('year').agg({'num_parts':
                                         pd.Series.mean})

parts_per_set.head()

plt.scatter(parts_per_set.index[:-2],parts_per_set.num_parts[:-2])

set_theme_count = sets["theme_id"].value_counts()
set_theme_count[:5]

"""<img src= "https://i.imgur.com/Sg4lcjx.png">"""

themes = pd.read_csv('themes.csv')
themes.head()

themes[themes.name == 'Star Wars']

sets[sets.theme_id == 18]

sets[sets.theme_id ==209]

set_theme_count = sets["theme_id"].value_counts()
set_theme_count[:5]

set_theme_count = pd.DataFrame({'id':set_theme_count.index,
                                'set_count':set_theme_count.values})
set_theme_count.head()

merge_df = pd.merge(set_theme_count,themes, on='id')
merge_df[:3]

plt.bar(merge_df.name[:10],merge_df.set_count[:10])

